name: Build and run tests

on:
  push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    - run: npm run test:integration
