name: Build and run tests

on:
  push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm run test
    #- run: npm run test:integration
      
    - run: echo hi > world.txt
    - uses: actions/upload-artifact@v2
      with:
        path: world.txt

    - run: echo "Hello World" > file.txt
    - uses: actions/upload-artifact@v1
      with:
        name: file
        path: file.txt

      #uses: actions/upload-artifact@v2
      #with:
       # name: screenshots
       # path: src

    #- name: Install puppeteer
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/puppeteer@3.0.0
      #uses: ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb
        #with:
        #  args: yarn
    
    #- name: Test
    #  uses: ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb
    #  with:
    #      args: npm run test:integration
    
    #- name: Upload a Build Artifact

  
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2

