name: Deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - run: npm ci
    - run: npm run build
#    - run: npm run test
#    - run: npm run test:integration

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.

