name: Deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: npm ci
      - run: npm run build
      #    - run: npm run test
      #    - run: npm run test:integration

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true,
          #        ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages-2 # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

